paths:
  input_audio_dir: "./assets/zeroth"
  noise_dir: "./assets/noises"
  output_dir: "./data/augmented_audio"
  label_dir: "./data/labels"
  hf_dataset_dir: "./data/hf_dataset"
  noise_catalog: "./data/noise/noise_catalog.csv"
  noise_resampled_dir: "./data/noise/resampled"
  raw_samples_path: "./data/zeroth/raw_samples_train.jsonl"
  alignment_output_dir: "./data/labels"

aligner:
  model_name: "large-v3"
  language: "ko"
  device: "cuda"
  compute_type: "float16"
  # When using CPU, float32 is recommended; adjust automatically in code.
  batch_size: 8
  vad_backend: "none"
  diarize: false
  rng_seed: 42

synthesis:
  insertion_type: "noise"
  min_gap_sec: 0.8
  insertion_duration_sec:
    min: 1.5
    max: 3.0
  crossfade_sec: 0.05
  context_window_sec: 0.75
  target_snr_db: 12.0
  loudness_target_lufs: -23.0
  true_peak_dbfs: -1.0
  insertions_per_file: 1
  rng_seed: 4242
  noise_categories: []

labelling:
  baseline_model_name: "openai/whisper-large-v3"
  include_silence_token: true

metadata:
  enable_tracking: true
  save_original_segments: true
